language: go

before_script:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.15.0

install:
    - go get golang.org/x/tools/cmd/cover
    - go get github.com/mattn/goveralls

script:
  - go test ./... -coverpkg=./... -v -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -repotoken $COVERALLS_TOKEN
  - echo go test ./... -bench=.
  - golangci-lint run --disable-all -E errcheck
