language: go

before_script:
    - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.15.0

script:
    - go test ./... -v -coverpkg=./...
    - go test ./... -bench=.
    - golangci-lint run --disable-all -E errcheck

deploy:
    provider: heroku
    api_key:
        secure: $HEROKU_TOKEN
    app:
        develop: leistungsnachweis-ateam-dev
        master: leistungsnachweis-ateam
    skip_cleanup: true
