language: go

before_script:
    - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.15.0

script:
    - echo go test -v
    - echo go test -bench=.
    - golangci-lint run --disable-all -E errcheck

deploy:
    provider: heroku
    api_key:
        secure: $HEROKU_TOKEN
    app:
        feature/testcoverage-buildstatus-badges: leistungsnachweis-ateam
